# Generated by Django 4.1 on 2023-04-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=256),
        ),
    ]
